In [1]:
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LogisticRegression

In [2]:
steps = [
    ("Standard_scalar", StandardScaler()),
    ("Classifier",LogisticRegression())
]

In [4]:
steps

[('Standard_scalar', StandardScaler()), ('Classifier', LogisticRegression())]

In [5]:
pipe = Pipeline(steps)

In [6]:
#Visualize Pipeline
from sklearn import set_config
set_config(display="diagram")

In [7]:
pipe

,steps,"[('Standard_scalar', ...), ('Classifier', ...)]"
,transform_input,None
,memory,None
,verbose,False
,copy,True
,with_mean,True
,with_std,True
,penalty,'l2'
,dual,False
,tol,0.0001
,C,1.0


In [8]:
#Create a dataset
from sklearn.datasets import make_classification
x,y = make_classification(n_samples=1000)

In [9]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(
    x,y, test_size=0.33, random_state=42
)

In [10]:
x_train

array([[-1.27596339, -0.68270793,  0.22143361, ...,  0.35835392,
         0.60902281,  0.87474326],
       [ 1.85073986, -0.70844749,  0.79328299, ...,  2.06292091,
         2.02171535,  0.01338047],
       [ 0.3076024 ,  2.25334502,  0.82245056, ..., -0.3647735 ,
        -0.28666959, -1.94525168],
       ...,
       [ 0.47838068, -0.98929543,  1.20133477, ..., -0.20589074,
         1.15461769, -0.15154781],
       [ 0.71856863,  0.16977844,  0.80393996, ..., -1.86149445,
        -1.13325909, -1.93291109],
       [-1.20545413,  1.72421294,  1.80777072, ..., -1.49745767,
         0.36778156, -0.94933359]], shape=(670, 20))

In [11]:
pipe.fit(x_train, y_train)

,steps,"[('Standard_scalar', ...), ('Classifier', ...)]"
,transform_input,None
,memory,None
,verbose,False
,copy,True
,with_mean,True
,with_std,True
,penalty,'l2'
,dual,False
,tol,0.0001
,C,1.0


In [13]:
y_pred = pipe.predict(x_test)

In [ ]:
# ##Example 2
# Displaying a pipeline with standard scalar, dimensionality reduction and then estimator


In [14]:
from sklearn.decomposition import PCA
from sklearn.svm import SVC

In [16]:
steps = [
    ("Scaling", StandardScaler()),
    ("PCA",PCA(n_components=3)),
    ("SVC",SVC())
]

In [17]:
pipe2 =Pipeline(steps)

In [18]:
#Can use single function from pipeline
pipe2['Scaling'].fit_transform(x_train)

array([[-1.32348356e+00, -7.40305672e-01,  2.38104144e-01, ...,
         4.05735642e-01,  6.13722638e-01,  8.70020177e-01],
       [ 1.98859864e+00, -7.66207860e-01,  8.02947821e-01, ...,
         2.11923565e+00,  2.00413752e+00,  7.76298545e-04],
       [ 3.53970184e-01,  2.21429699e+00,  8.31758064e-01, ...,
        -3.21181422e-01, -2.67845013e-01, -1.97577647e+00],
       ...,
       [ 5.34873722e-01, -1.04883017e+00,  1.20600057e+00, ...,
        -1.61466018e-01,  1.15071369e+00, -1.65661005e-01],
       [ 7.89302166e-01,  1.17566627e-01,  8.13474235e-01, ...,
        -1.82574614e+00, -1.10108410e+00, -1.96332297e+00],
       [-1.24879388e+00,  1.68182189e+00,  1.80500711e+00, ...,
        -1.45980158e+00,  3.76285674e-01, -9.70746175e-01]],
      shape=(670, 20))

In [19]:
pipe2.fit(x_train, y_train)

,steps,"[('Scaling', ...), ('PCA', ...), ...]"
,transform_input,None
,memory,None
,verbose,False
,copy,True
,with_mean,True
,with_std,True
,n_components,3
,copy,True
,whiten,False
,svd_solver,'auto'


In [22]:
pipe2.predict(x_test)

array([1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1,
       0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1,
       1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0,
       0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1,
       0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1,
       1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0,
       1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1,
       0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0,
       0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0,
       1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0,
       0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0,
       0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0,

In [24]:
#Example 3: More Complex Pipeline
from sklearn.impute import SimpleImputer
import numpy as np

In [ ]:
#For numeric processing pipeline
numeric_processor = Pipeline(
    steps = [
        ("impute_mean", SimpleImputer(missing_values=np.nan,strategy="mean")),
        ("Sclar", StandardScaler())
    ]
)

In [26]:
numeric_processor

,steps,"[('impute_mean', ...), ('Sclar', ...)]"
,transform_input,None
,memory,None
,verbose,False
,missing_values,nan
,strategy,'mean'
,fill_value,None
,copy,True
,add_indicator,False
,keep_empty_features,False
,copy,True


In [27]:
#For categorical processing pipeline
from sklearn.preprocessing import OneHotEncoder
categorical_processor = Pipeline(
    steps = [
        ("impute_constant", SimpleImputer(fill_value="missing",strategy="constant")),
        ("OneHot",OneHotEncoder(handle_unknown="ignore"))
    ]
)

In [28]:
categorical_processor

,steps,"[('impute_constant', ...), ('OneHot', ...)]"
,transform_input,None
,memory,None
,verbose,False
,missing_values,nan
,strategy,'constant'
,fill_value,'missing'
,copy,True
,add_indicator,False
,keep_empty_features,False
,categories,'auto'


In [29]:
#COmbine Processing techniques
from sklearn.compose import ColumnTransformer

In [30]:
preprocessor = ColumnTransformer(
    [("Categorical",categorical_processor,["gender","City"]),
     ("numerical",numeric_processor,["age","height"])]
)

In [31]:
preprocessor

,transformers,"[('Categorical', ...), ('numerical', ...)]"
,remainder,'drop'
,sparse_threshold,0.3
,n_jobs,None
,transformer_weights,None
,verbose,False
,verbose_feature_names_out,True
,force_int_remainder_cols,'deprecated'
,missing_values,nan
,strategy,'constant'
,fill_value,'missing'


In [34]:
from sklearn.pipeline import make_pipeline
pipe = make_pipeline(preprocessor, LogisticRegression())

In [35]:
pipe

,steps,"[('columntransformer', ...), ('logisticregression', ...)]"
,transform_input,None
,memory,None
,verbose,False
,transformers,"[('Categorical', ...), ('numerical', ...)]"
,remainder,'drop'
,sparse_threshold,0.3
,n_jobs,None
,transformer_weights,None
,verbose,False
,verbose_feature_names_out,True


In [36]:
#Hyperparameter Tuning Using Machine Learning
import numpy as np
from sklearn.pipeline import make_pipeline
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import GridSearchCV

In [37]:
import seaborn as sns

In [38]:
df = sns.load_dataset('tips')
df.head()

,total_bill,tip,sex,smoker,day,time,size
0,16.99,1.01,Female,No,Sun,Dinner,2
1,10.34,1.66,Male,No,Sun,Dinner,3
2,21.01,3.50,Male,No,Sun,Dinner,3
3,23.68,3.31,Male,No,Sun,Dinner,2
4,24.59,3.61,Female,No,Sun,Dinner,4


In [39]:
x = df.iloc[:,1:]
y = df['total_bill']

In [40]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.2)

In [41]:
##Pipeline
numeric_processor = Pipeline(
    steps=[
        ("impute_mean", SimpleImputer(missing_values=np.nan, strategy="mean")),
        ("Scalar",StandardScaler()),
    ]
)

In [42]:
categorical_processor = Pipeline(
    steps = [
        (
            "imputation_constant", 
            SimpleImputer(fill_value="missing", strategy="constant"),
        ),
        ("onehot",OneHotEncoder(handle_unknown="ignore")),
    ]
)

In [43]:
preprocessor = ColumnTransformer(
    [
        ("categorical",categorical_processor,["sex","smoker","day","time"]),
        ("numerical",numeric_processor,["tip","size"]),
    ]
)

In [44]:
pipe = Pipeline(
    steps = [
        ("preprocessor",preprocessor),("regressor",RandomForestRegressor())
    ]
)

In [45]:
from sklearn import set_config
set_config(display='diagram')

In [46]:
pipe

,steps,"[('preprocessor', ...), ('regressor', ...)]"
,transform_input,None
,memory,None
,verbose,False
,transformers,"[('categorical', ...), ('numerical', ...)]"
,remainder,'drop'
,sparse_threshold,0.3
,n_jobs,None
,transformer_weights,None
,verbose,False
,verbose_feature_names_out,True


In [47]:
pipe.fit(x_train,y_train)

,steps,"[('preprocessor', ...), ('regressor', ...)]"
,transform_input,None
,memory,None
,verbose,False
,transformers,"[('categorical', ...), ('numerical', ...)]"
,remainder,'drop'
,sparse_threshold,0.3
,n_jobs,None
,transformer_weights,None
,verbose,False
,verbose_feature_names_out,True


In [48]:
pipe.predict(x_test)

array([41.4311    , 22.03346   , 32.5562    , 20.58416333, 12.42918067,
       18.8518    , 21.5154    , 13.53812   , 13.73249167, 15.28510333,
       22.6088    , 34.0518    , 39.015     , 28.68834   , 30.6492    ,
       10.58325095, 33.1114    , 21.20366667, 17.7972    , 38.0989    ,
       11.90343524, 13.0758    , 19.36476667, 19.968     , 22.2481    ,
       10.16515833, 11.5708    , 12.4921    , 19.0279    , 38.0989    ,
       25.08203333, 11.2169    , 25.19343333, 18.0065    , 10.82886   ,
       12.42918067, 10.35856333, 14.0344    , 27.8887    , 18.8986    ,
       19.23816667, 31.8965    , 16.05630833, 15.13554   , 20.84126667,
       29.1423    , 13.23061333, 13.73249167, 12.04564437])

In [51]:
import warnings
warnings.filterwarnings('ignore')

In [56]:
#Hyperparameter Tuning
param_grid = {
    "regressor__n_estimators":[200,500],
    "regressor__max_features":["auto","sqrt","log2"],
    "regressor__max_depth":[4,5,6,7,8]
}

In [57]:
grid_search = GridSearchCV(pipe, param_grid=param_grid, n_jobs=1)

In [58]:
grid_search.fit(x_train,y_train)

,estimator,Pipeline(step...Regressor())])
,param_grid,"{'regressor__max_depth': [4, 5, ...], 'regressor__max_features': ['auto', 'sqrt', ...], 'regressor__n_estimators': [200, 500]}"
,scoring,None
,n_jobs,1
,refit,True
,cv,None
,verbose,0
,pre_dispatch,'2*n_jobs'
,error_score,nan
,return_train_score,False
,transformers,"[('categorical', ...), ('numerical', ...)]"


In [59]:
grid_search = GridSearchCV(pipe, param_grid=param_grid, n_jobs=1)
grid_search.fit(x_train, y_train)

,estimator,Pipeline(step...Regressor())])
,param_grid,"{'regressor__max_depth': [4, 5, ...], 'regressor__max_features': ['auto', 'sqrt', ...], 'regressor__n_estimators': [200, 500]}"
,scoring,None
,n_jobs,1
,refit,True
,cv,None
,verbose,0
,pre_dispatch,'2*n_jobs'
,error_score,nan
,return_train_score,False
,transformers,"[('categorical', ...), ('numerical', ...)]"


In [60]:
grid_search.best_params_

{'regressor__max_depth': 5,
 'regressor__max_features': 'sqrt',
 'regressor__n_estimators': 500}

In [61]:
pipe = Pipeline(
    steps = [
        ("preprocessor",preprocessor),("regressor",RandomForestRegressor(max_depth=5,max_features='sqrt',n_estimators=500))
    ]
)

In [62]:
pipe.fit(x_train, y_train)

,steps,"[('preprocessor', ...), ('regressor', ...)]"
,transform_input,None
,memory,None
,verbose,False
,transformers,"[('categorical', ...), ('numerical', ...)]"
,remainder,'drop'
,sparse_threshold,0.3
,n_jobs,None
,transformer_weights,None
,verbose,False
,verbose_feature_names_out,True


In [64]:
y_pred = pipe.predict(x_test)

In [66]:
#Evaluate the model
from sklearn.metrics import mean_absolute_error
mean_absolute_error(y_test, y_pred)
from sklearn.metrics import r2_score
r2_score(y_test, y_pred)

0.5179550120289045